name: Update Trackers Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:      # Lets you manually run it

jobs:
  combine-trackers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download and combine trackers
      run: |
        # Download both lists
        curl -s https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt -o ngosang.txt
        curl -s https://cf.trackerslist.com/all.txt -o cf.txt
        
        # Combine, remove duplicates, and clean up
        cat ngosang.txt cf.txt | grep -v '^$' | sort -u > combined.txt
        
        # Commit changes (if any)
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add combined.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update trackers" && git push)
